export const FALLBACK_PRODUCTS = [
  {
    _id: 'prod-seed-1',
    name: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    slug: 'sony-wh-1000xm5-headphones',
    description: 'Industry-leading noise cancellation with two processors and eight microphones for unprecedented sound quality and crystal-clear hands-free calling.',
    price: 349.99,
    stock: 24,
    category: { _id: 'cat-elec', name: 'Electronics', slug: 'electronics' },
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-2',
    name: 'Apple MacBook Air 13-inch M2 Chip Liquid Retina Display',
    slug: 'apple-macbook-air-m2',
    description: 'Strikingly thin design with blazing-fast 8-core CPU and 10-core GPU, up to 18 hours of battery life, and MagSafe charging.',
    price: 1099.00,
    stock: 12,
    category: { _id: 'cat-elec', name: 'Electronics', slug: 'electronics' },
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-3',
    name: 'Samsung Galaxy S24 Ultra 5G AI Smartphone',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Titanium frame, built-in S Pen, 200MP camera with Nightography Zoom, and Snapdragon 8 Gen 3 processor.',
    price: 1299.99,
    stock: 15,
    category: { _id: 'cat-elec', name: 'Electronics', slug: 'electronics' },
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-4',
    name: 'Dell XPS 15 OLED InfinityEdge Touchscreen Laptop',
    slug: 'dell-xps-15-touch',
    description: '13th Gen Intel Core i7, 3.5K OLED immersive display, NVIDIA GeForce RTX 4060 graphics with premium machined aluminum chassis.',
    price: 1899.00,
    stock: 8,
    category: { _id: 'cat-elec', name: 'Electronics', slug: 'electronics' },
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-5',
    name: 'Genuine Vintage Men Brown Biker Leather Jacket',
    slug: 'mens-vintage-leather-jacket',
    description: 'Crafted from 100% genuine supple lambskin leather with reinforced stitching, quilted shoulder accents, and zippered cuffs.',
    price: 189.50,
    stock: 18,
    category: { _id: 'cat-fash', name: 'Fashion & Apparel', slug: 'fashion-apparel' },
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-6',
    name: 'Nike Air Max 270 Athletic Lifestyle Running Shoes',
    slug: 'nike-air-max-270',
    description: 'Large Air unit delivers unmatched all-day comfort with breathable engineered mesh upper and dual-density foam sole.',
    price: 159.99,
    stock: 30,
    category: { _id: 'cat-fash', name: 'Fashion & Apparel', slug: 'fashion-apparel' },
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-7',
    name: 'Levi 511 Slim Fit Stretch Denim Indigo Jeans',
    slug: 'levis-511-slim-jeans',
    description: 'A modern slim with room to move. Added stretch for all-day comfort with classic 5-pocket styling and iconic red tab.',
    price: 69.50,
    stock: 45,
    category: { _id: 'cat-fash', name: 'Fashion & Apparel', slug: 'fashion-apparel' },
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-8',
    name: 'Heavy-Duty Pre-Seasoned Cast Iron Skillet 12-Inch',
    slug: 'cast-iron-skillet-12',
    description: 'Superior heat retention and even cooking for stovetop, oven, grill, or campfire. Naturally non-stick seasoned surface.',
    price: 49.99,
    stock: 22,
    category: { _id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen' },
    images: ['https://images.unsplash.com/photo-1584990347449-397444158913?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-9',
    name: 'Italian Automatic Espresso Machine with Steam Frother',
    slug: 'italian-espresso-machine',
    description: '15-bar professional Italian pump brews rich espresso and silky cappuccino microfoam in under 45 seconds.',
    price: 299.99,
    stock: 14,
    category: { _id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen' },
    images: ['https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-10',
    name: 'Smart RGB-IC Ambient Floor Lamp with Alexa & App Control',
    slug: 'smart-rgb-floor-lamp',
    description: '16 million colors and 300+ dynamic lighting modes with music sync for modern minimalist living room aesthetics.',
    price: 89.00,
    stock: 26,
    category: { _id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen' },
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-11',
    name: 'Ultra-Quiet Bladeless Oscillating Tower Air Purifier Fan',
    slug: 'bladeless-tower-fan',
    description: 'High-velocity quiet cooling with HEPA air filtration, magnetic remote control, sleep timer, and child-safe design.',
    price: 129.99,
    stock: 19,
    category: { _id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen' },
    images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80'],
  },
  {
    _id: 'prod-seed-12',
    name: 'German High-Carbon Stainless Steel Knife Set 15-Piece',
    slug: 'knife-set-15-piece',
    description: 'Ultra-sharp forged German steel with ergonomic pakkawood handles and self-sharpening hardwood storage block.',
    price: 99.50,
    stock: 35,
    category: { _id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen' },
    images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&auto=format&fit=crop&q=80'],
  },
];
